<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>加载中</title>
</head>
<body>

<script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
<script>
 var queryparam = '';
     window.onload = function () {
            $.ajax({
                type: "GET",
                url: "http://api.longxx.cn/bak/gg/api/api.php",
                dataType: "jsonp",
                jsonp: "callback",
                jsonpCallback: "callback",
                success: function(res) {
                  queryparam = decodeURI(window.location.href.split('/').slice(3).join('/'))；
                  
                  location.href = res.domainname + queryparam;

                  function getCaption(obj){
                      var index=obj.lastIndexOf("\?");
                      obj=obj.substring(index+1,obj.length);
                      return obj;
                  }

                },
                error: function(res) {
                  location.href = "http://qq.com";
                }
            });
       
    }
</script>
</body>

</html>